platform :ios, "7.0"

pod 'AFNetworking'
pod 'BlocksKit'
pod 'CocoaLumberjack'
pod 'Masonry'
pod 'MBProgressHUD'
pod 'MJExtension'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'TPKeyboardAvoiding'
pod 'MLTransition'
pod 'FMDB'
pod 'CocoaAsyncSocket', '~> 7.4.3'
pod 'Shimmer'
pod 'FlatUIKit'
pod 'AsyncDisplayKit'
pod 'RESideMenu'
pod 'SWTableViewCell'
pod 'MWPhotoBrowser'
pod 'WMPageController'

